[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["/server/**"]

[deploy]
startCommand = "node server.js"
rootDirectory = "/server"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.service]
# Memaksa Railway mengarahkan traffic ke port yang benar
tcpPort = 8080
